Traceback (most recent call last):
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/nicolekeeney/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#map projection from ICESat-2 data (can be viewed in is2.projection.attrs['srid'])
out_proj = 'EPSG:3411'
out_lons = is2_ds.longitude
out_lats = is2_ds.latitude

#initialize map projection and project data to it
mapProj = pyproj.Proj("+init=" + out_proj)
xptsIS2, yptsIS2 = mapProj(out_lons, out_lats)
xptsCDR, yptsCDR = mapProj(cdr_da.longitude.values, cdr_da.latitude.values)

#regrid data 
cdr_regridded = regridToICESat2(cdr_da, xptsCDR, yptsCDR, xptsIS2, yptsIS2)
cdr_regridded = xr.DataArray(data = cdr_regridded, 
                             dims = ['time', 'y', 'x'], 
                             coords = {'latitude': (('y','x'), out_lats), 'longitude': (('y','x'), out_lons), 'time': pio_da.time.values}, 
                             name = cdr_da.name)
cdr_regridded = cdr_regridded.to_dataset()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/8v/cr06mz0n3bjd5jr12_9v6n200000gn/T/ipykernel_71198/1576104076.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;31m#regrid data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0mcdr_regridded[0m [0;34m=[0m [0mregridToICESat2[0m[0;34m([0m[0mcdr_da[0m[0;34m,[0m [0mxptsCDR[0m[0;34m,[0m [0myptsCDR[0m[0;34m,[0m [0mxptsIS2[0m[0;34m,[0m [0myptsIS2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m cdr_regridded = xr.DataArray(data = cdr_regridded, 
[0m[1;32m     14[0m                              [0mdims[0m [0;34m=[0m [0;34m[[0m[0;34m'time'[0m[0;34m,[0m [0;34m'y'[0m[0;34m,[0m [0;34m'x'[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m                              [0mcoords[0m [0;34m=[0m [0;34m{[0m[0;34m'latitude'[0m[0;34m:[0m [0;34m([0m[0;34m([0m[0;34m'y'[0m[0;34m,[0m[0;34m'x'[0m[0;34m)[0m[0;34m,[0m [0mout_lats[0m[0;34m)[0m[0;34m,[0m [0;34m'longitude'[0m[0;34m:[0m [0;34m([0m[0;34m([0m[0;34m'y'[0m[0;34m,[0m[0;34m'x'[0m[0;34m)[0m[0;34m,[0m [0mout_lons[0m[0;34m)[0m[0;34m,[0m [0;34m'time'[0m[0;34m:[0m [0mpio_da[0m[0;34m.[0m[0mtime[0m[0;34m.[0m[0mvalues[0m[0;34m}[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/xarray/core/dataarray.py[0m in [0;36m__init__[0;34m(self, data, coords, dims, name, attrs, indexes, fastpath)[0m
[1;32m    408[0m             [0mdata[0m [0;34m=[0m [0m_check_data_shape[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mcoords[0m[0;34m,[0m [0mdims[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    409[0m             [0mdata[0m [0;34m=[0m [0mas_compatible_data[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 410[0;31m             [0mcoords[0m[0;34m,[0m [0mdims[0m [0;34m=[0m [0m_infer_coords_and_dims[0m[0;34m([0m[0mdata[0m[0;34m.[0m[0mshape[0m[0;34m,[0m [0mcoords[0m[0;34m,[0m [0mdims[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    411[0m             [0mvariable[0m [0;34m=[0m [0mVariable[0m[0;34m([0m[0mdims[0m[0;34m,[0m [0mdata[0m[0;34m,[0m [0mattrs[0m[0;34m,[0m [0mfastpath[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    412[0m             indexes = dict(

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/xarray/core/dataarray.py[0m in [0;36m_infer_coords_and_dims[0;34m(shape, coords, dims)[0m
[1;32m    138[0m     [0;32mif[0m [0mutils[0m[0;34m.[0m[0mis_dict_like[0m[0;34m([0m[0mcoords[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    139[0m         [0;32mfor[0m [0mk[0m[0;34m,[0m [0mv[0m [0;32min[0m [0mcoords[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 140[0;31m             [0mnew_coords[0m[0;34m[[0m[0mk[0m[0;34m][0m [0;34m=[0m [0mas_variable[0m[0;34m([0m[0mv[0m[0;34m,[0m [0mname[0m[0;34m=[0m[0mk[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    141[0m     [0;32melif[0m [0mcoords[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    142[0m         [0;32mfor[0m [0mdim[0m[0;34m,[0m [0mcoord[0m [0;32min[0m [0mzip[0m[0;34m([0m[0mdims[0m[0;34m,[0m [0mcoords[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/xarray/core/variable.py[0m in [0;36mas_variable[0;34m(obj, name)[0m
[1;32m    119[0m     [0;32melif[0m [0misinstance[0m[0;34m([0m[0mobj[0m[0;34m,[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    120[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0mobj[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m,[0m [0mDataArray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 121[0;31m             raise TypeError(
[0m[1;32m    122[0m                 [0;34m"Using a DataArray object to construct a variable is"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    123[0m                 [0;34m" ambiguous, please extract the data using the .data property."[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.
TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.

