Traceback (most recent call last):
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Read in the raw monthly gridded winter Arctic sea ice data from local storage (includes prelim data in this case)
IS2SITMOGR4_all = read_IS2SITMOGR4(data_type='netcdf', local_data_path='/data/IS2SITMOGR4/', version='') 
IS2SITMOGR4_all
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# Read in the raw monthly gridded winter Arctic sea ice data from local storage (includes prelim data in this case)[39;00m
[0;32m----> 2[0m IS2SITMOGR4_all [38;5;241m=[39m [43mread_IS2SITMOGR4[49m[43m([49m[43mdata_type[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mnetcdf[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mlocal_data_path[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m/data/IS2SITMOGR4/[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mversion[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m)[49m 
[1;32m      3[0m IS2SITMOGR4_all

File [0;32m~/GitHub/icesat2-book/content/utils/read_data_utils.py:139[0m, in [0;36mread_IS2SITMOGR4[0;34m(data_type, version, local_data_path, bucket_name, persist, download)[0m
[1;32m    137[0m filenames [38;5;241m=[39m glob[38;5;241m.[39mglob(local_data_path[38;5;241m+[39mversion[38;5;241m+[39m[38;5;124m'[39m[38;5;124m/*.nc[39m[38;5;124m'[39m)
[1;32m    138[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(filenames) [38;5;241m==[39m [38;5;241m0[39m: 
[0;32m--> 139[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNo files, exit[39m[38;5;124m"[39m)
[1;32m    140[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    142[0m dates [38;5;241m=[39m [pd[38;5;241m.[39mto_datetime(file[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124mIS2SITMOGR4_01_[39m[38;5;124m"[39m)[[38;5;241m1[39m][38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m_[39m[38;5;124m"[39m)[[38;5;241m0[39m], [38;5;28mformat[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124m%[39m[38;5;124mY[39m[38;5;124m%[39m[38;5;124mm[39m[38;5;124m"[39m)  [38;5;28;01mfor[39;00m file [38;5;129;01min[39;00m filenames]

[0;31mValueError[0m: No files, exit

